### ISSUE TITLE
Implement date/time support in kernel

### ISSUE THREAD

**Issue by SirCmpwn** [KnightOS/KnightOS#168]
We have a real time clock on some platforms, so let's support it. This is being implemented in `time.asm` on Flash page 2.

* [x] setClock
* [x] getTimeInTicks
* [x] convertTimeFromTicks
* [ ] convertTimeToTicks
* [x] getTime (depends on convertTimeToTicks)
* [x] Update castle to actually show the time
* [x] Add time settings to settings app

**Comment by SirCmpwn** [comment]
Note: @Willem3141 is working on this.

**Comment by EphraimB** [comment]
Isn't "update castle to actually show the time" already done?

**Comment by SirCmpwn** [comment]
Yep.

**Comment by EphraimB** [comment]
Is ConvertTimeToTicks almost done?

**Comment by SirCmpwn** [comment]
Hey @Willem3141, any updates on this?

**Comment by Willem3141** [comment]
@SirCmpwn Progress is a bit slower than I expected because of study-related things, but it is now really almost done. The code to compute the correct year from a timestamp is done and works also in corner-cases (and is unit-tested). The only remaining thing is getting the month and day, which I'll try to finish next weekend.

**Comment by SirCmpwn** [comment]
Thanks for the update. FYI, @boos1993 has been tinkering with this and I think has got something good going.

**Comment by Willem3141** [comment]
Date/time support has been finished (see https://github.com/KnightOS/kernel/pull/168).
